"""Generates the static Maafushi map artwork (public/map/maafushi.svg).
Run: python scripts/generate-map.py. Seeded, so the output is stable."""
import math, random, json
random.seed(7)
A=(52,176); B=(548,420)
L=math.dist(A,B); ux,uy=((B[0]-A[0])/L,(B[1]-A[1])/L); px,py=(-uy,ux)  # perp points "south-west"(down-left)
def cl(t): return (A[0]+ux*L*t, A[1]+uy*L*t)
def profile(t, maxw):
    # tapered ends, slightly fatter at SE third
    s = math.sin(math.pi*t)**0.33
    return maxw*s*(0.85+0.3*t)
def outline(maxw, noise, n=48, ph=0.0):
    pts=[]
    for i in range(n+1):
        t=i/n; c=cl(t); w=profile(t,maxw)+noise*math.sin(t*23+ph)+noise*0.6*math.sin(t*41+ph*2)
        pts.append((c[0]-px*w, c[1]-py*w))  # north/east side
    for i in range(n,-1,-1):
        t=i/n; c=cl(t); w=profile(t,maxw)+noise*math.sin(t*19+ph+1)+noise*0.6*math.sin(t*37+ph)
        pts.append((c[0]+px*w, c[1]+py*w))
    # dedupe tips
    return pts
def catmull(pts):
    # closed catmull-rom to bezier
    n=len(pts); d=f"M{pts[0][0]:.1f} {pts[0][1]:.1f}"
    for i in range(n):
        p0=pts[(i-1)%n]; p1=pts[i]; p2=pts[(i+1)%n]; p3=pts[(i+2)%n]
        c1=(p1[0]+(p2[0]-p0[0])/6, p1[1]+(p2[1]-p0[1])/6)
        c2=(p2[0]-(p3[0]-p1[0])/6, p2[1]-(p3[1]-p1[1])/6)
        d+=f"C{c1[0]:.1f} {c1[1]:.1f} {c2[0]:.1f} {c2[1]:.1f} {p2[0]:.1f} {p2[1]:.1f}"
    return d+"Z"
def thin(pts,k): return pts[::k]
island=thin(outline(50,2.4,ph=0.3),2)
veg=thin(outline(36,2.6,ph=1.1),2)
reef=thin(outline(104,8,ph=2.0),2)
lagoon=thin(outline(78,5,ph=2.7),2)
out={'island':catmull(island),'veg':catmull(veg),'reef':catmull(reef),'lagoon':catmull(lagoon)}
# island blocks: t in 0.12..0.5, within veg width
blocks=[]
for i in range(140):
    t=random.uniform(0.06,0.5); c=cl(t); w=profile(t,36)*0.82
    o=random.uniform(-w,w); x=c[0]+px*o; y=c[1]+py*o
    if any(math.dist((x,y),(b[0],b[1]))<12.5 for b in blocks): continue
    blocks.append((round(x,1),round(y,1),random.choice([10,12,14]),random.choice([8,9,10])))
out['blocks']=blocks
palms=[]
for i in range(140):
    t=random.uniform(0.5,0.95); c=cl(t); w=profile(t,36)*0.88
    o=random.uniform(-w,w); x=c[0]+px*o; y=c[1]+py*o
    if any(math.dist((x,y),p[:2])<9 for p in palms): continue
    palms.append((round(x,1),round(y,1),round(random.uniform(3,5.5),1)))
out['palms']=palms
def at(t,o): c=cl(t); return (round(c[0]+px*o,1), round(c[1]+py*o,1))
out['pts']={k:at(*v) for k,v in {'driftwood':(0.7,38),'reef':(0.655,102),'bikini':(0.955,6),'jetty':(0.46,-66),'island':(0.27,2),'teashop':(0.4,18),'cafe':(0.05,4),'pitch':(0.55,-14)}.items()}
out['axis']={'ux':ux,'uy':uy,'px':px,'py':py}

print(out['pts'], out['axis'])

# ---------------------------------------------------------------------------
# Write the static artwork as an SVG file (no JS, cached across pages). Hotspots are added
# on top by the IslandMap island using the coordinates in src/data/places.ts.
# ---------------------------------------------------------------------------
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
p = out['pts']; ang = math.degrees(math.atan2(uy, ux))
# A quiet line drawing in the site palette: sea-tinted water, hairline
# outlines, outlined island blocks, a dotted reef edge. Square corners.
INK = '#1E1A17'; SEA = '#3E6F70'; CREAM = '#F6F2EC'; TAUPE = '#8B8178'
blocks = ''.join(f'<rect x="{round(x-w/2,1)}" y="{round(y-h/2,1)}" width="{w}" height="{h}" transform="rotate({ang:.1f} {x} {y})"/>' for x,y,w,h in out['blocks'])
palms = ''.join(f'<circle cx="{x}" cy="{y}" r="{round(r*0.42,1)}"/>' for x,y,r in out['palms'])
dx,dy = p['driftwood']; rx,ry = p['reef']; jx,jy = p['jetty']; bx,by = p['bikini']; qx,qy = p['pitch']
umb = ''.join(f'<path transform="translate({round(bx+ox,1)} {round(by+oy,1)})" d="M-4 0h8M0 0v4"/>' for ox,oy in [(-22,-20),(-12,-15),(-2,-9)])
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 560" width="600" height="560">
  <!-- Generated by scripts/generate-map.py. Illustration of Maafushi, not to scale. -->
  <style>
    .map-walk {{ animation: walk 2.4s linear infinite; }}
    .map-route {{ animation: walk 5s linear infinite; }}
    @keyframes walk {{ to {{ stroke-dashoffset: -20; }} }}
    @media (prefers-reduced-motion: reduce) {{ .map-walk, .map-route {{ animation: none; }} }}
  </style>
  <defs>
    <pattern id="map-water" width="28" height="14" patternUnits="userSpaceOnUse"><path d="M0 10h10" fill="none" stroke="{SEA}" stroke-opacity=".16" stroke-width=".6"/></pattern>
  </defs>
  <rect width="600" height="560" fill="#DCE6E4"/>
  <rect width="600" height="560" fill="url(#map-water)"/>
  <ellipse cx="548" cy="100" rx="40" ry="16" fill="#EAF0EE" stroke="{SEA}" stroke-opacity=".35" stroke-width=".6" transform="rotate(-12 548 100)"/>
  <path d="M520 104C536 94 560 92 578 96C566 100 544 104 524 110Z" fill="{CREAM}" stroke="{INK}" stroke-width=".6"/>
  <path class="map-route" d="M{jx+20} {jy-8}C380 160 470 130 528 112" fill="none" stroke="{SEA}" stroke-width="1" stroke-dasharray="2 6"/>
  <path d="{out['reef']}" fill="#D2DEDB"/>
  <path d="{out['reef']}" fill="none" stroke="{SEA}" stroke-opacity=".8" stroke-width=".8" stroke-dasharray="1 4"/>
  <path d="{out['lagoon']}" fill="#EAF0EE"/>
  <path d="{out['island']}" fill="{CREAM}" stroke="{INK}" stroke-width=".8"/>
  <path d="{out['veg']}" fill="none" stroke="{TAUPE}" stroke-opacity=".55" stroke-width=".5" stroke-dasharray="2 3"/>
  <g fill="{TAUPE}" fill-opacity=".55">{palms}</g>
  <g fill="none" stroke="{TAUPE}" stroke-width=".6">{blocks}</g>
  <rect x="{qx-17}" y="{qy-10}" width="34" height="20" fill="none" stroke="{TAUPE}" stroke-width=".6" transform="rotate({ang:.1f} {qx} {qy})"/>
  <path d="M{jx+18} {jy+40}L{jx} {jy}l28 13" stroke="{INK}" stroke-width="1.2" fill="none"/>
  <g stroke="{INK}" stroke-width=".7" fill="none">{umb}</g>
  <g transform="translate({dx} {dy}) rotate({ang:.1f})"><rect x="-15" y="-8" width="30" height="16" fill="{CREAM}" stroke="{INK}" stroke-width="1"/><rect x="-10" y="-4" width="20" height="8" fill="none" stroke="{INK}" stroke-width=".6"/></g>
  <path class="map-walk" d="M{round(dx-4,1)} {round(dy+10,1)}C{round(dx-8,1)} {round(dy+26,1)} {round(rx+14,1)} {round(ry-24,1)} {rx} {ry}" fill="none" stroke="{INK}" stroke-width="1.2" stroke-dasharray="2 5"/>
  <g transform="translate(44 508)" fill="none" stroke="{INK}" stroke-width=".8"><path d="M0-22L6 4L0 0L-6 4Z"/><path d="M-3 12v10M-3 12l6 10M3 12v10"/></g>
</svg>
'''
dest = ROOT / 'public' / 'map' / 'maafushi.svg'
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(svg, encoding='utf-8')
print('wrote', dest.relative_to(ROOT), len(svg)//1024, 'KB')
